site_name: cddlc

theme:
  name: material

  features:
    - content.code.copy
    - content.code.select

    # Enable when we fix repos
    # - content.action.edit
    # - content.action.view


  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/styles.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      base_path: .
  - pymdownx.inlinehilite
  - footnotes
  - attr_list
  - md_in_html

nav:
  - index.md
  - Installation: installation.md
  - Language: 
    - language/index.md
    - Primitives: language/primitives.md
    - Fixed Values: language/values_fixed.md
    - Sockets/Plugs: language/sockets_plugs.md
    - References: language/reference.md
  - Configuring Builds:
    - builds/index.md
 